### ISSUE TITLE
fedsd does not work with Pandas 2.0

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1834]
The `fedsd` utility for generating sequence diagrams fails with Pandas 2.0 with the following error:
```
Building the communication diagram for the following trace files: federate__c.lft federate__i.lft federate__t.lft rti.lft in trace_svg.html
Traceback (most recent call last):
  File "/Users/eal/lingua-franca-intellij/util/tracing/visualization/fedsd.py", line 137, in <module>
    trace_df = trace_df.append(fed_df, sort=False, ignore_index=True)
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```
According to [this page](https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append), append has been removed and must be replaced with concat.
